### ISSUE TITLE
blank numeric treated as string

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#59] opened 2018-05-09 12:51 UTC
We need conditional logic to replace a blank numeric with a period (.) in the adapter

**Comment by boemska-nik** [comment] 2019-10-04 14:52
Can you elaborate on this? On the way in or on the way back? Do you have an example?

**Comment by cj13579** [comment] 2020-03-05 13:37
This issue is a dupe of #67 which has an associated PR. Closing.

**Closed by cj13579** 2020-03-05 13:37 UTC
Labels: duplicate, enhancement
